-- migrate:up
create table
    display_group (
        id text NOT NULL primary key,
        created timestamptz DEFAULT now () NOT NULL,
        modified timestamptz DEFAULT now () NOT NULL,
        version integer NOT NULL DEFAULT 1,
        parent_id text REFERENCES display_group (id) ON DELETE CASCADE,
        level integer NOT NULL,
        name text not null
    );

create table
    display_group_period (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key,
        created timestamptz DEFAULT now () NOT NULL,
        modified timestamptz DEFAULT now () NOT NULL,
        version integer NOT NULL DEFAULT 1,
        dg_id text NOT NULL REFERENCES display_group (id) ON DELETE CASCADE,
        start_date date NOT NULL,
        end_date date NOT NULL
    );

-- migrate:down