-- migrate:up
create type audit_action as enum ('create', 'update', 'delete');

create table
    audit (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key,
        created timestamptz DEFAULT now () NOT NULL,
        action audit_action not null,
        table_name text not null,
        user_id text,
        data jsonb not null
    );

-- migrate:down