-- migrate:up
ALTER TABLE display_group
DROP COLUMN parent_id CASCADE;

ALTER TABLE display_group
DROP COLUMN id CASCADE;

ALTER TABLE display_group
ADD COLUMN id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key;

ALTER TABLE display_group
ADD COLUMN parent_id integer REFERENCES display_group (id) on delete CASCADE;

alter table display_group
add column dg_id text not null;

-- migrate:down